<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<script type="text/javascript">
	// 当一个Promise错误最初未被处理，但是稍后又得到了处理，则会触发rejectionhandled事件：

	window.addEventListener("rejectionhandled", event => {
  		console.log("没有处理, 之后又处理了" + event);
	}, false);

	// 当 Promise 被拒绝，但没有提供reject函数来处理该rejection 时，会派发此事件。
	window.addEventListener("unhandledrejection", event => {
  		/* 你可以在这里添加一些代码，以便检查
     	event.promise 中的 promise 和
     	event.reason 中的 rejection 原因 */
     	console.log(event.promise)
     	console.log(event.reason)
     	console.log('promise 错误捕获')
 	 	event.preventDefault();//默认操作会打印错误信息
	}, false);

	var p = new Promise((resolve, reject) => {
		reject('错误了')
	})
	// .then(res => {
	// 	console.log(res)
	// })
	setTimeout(() => {
		p.catch(err => {
			console.log(err)
		})
	})
	
</script>
</body>
</html>