<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<!-- 
1.async函数返回值
   返回值为一个promise对象, 结果状态由async函数的执行的返回值决定
   1. 抛出异常 async函数体内没有处理  则.then指定的错误回调函数处理
   2. return 一个promise对象 async函数返回的promise对象结果状态跟return的promise对象的一致
   3. 其他值 返回一个成功状态的promise对象, value就是该值

2.await 表达式
  如果是promise对象, await返回的是promise成功的值  让出线程
  如果是其他值, 直接将此值作为await的返回值 同样会让出线程

3.注意await必须写在async函数中, 但async函数中可以没有await
  (1) 如果await的promise为失败状态, 就会抛出异常, 需要通过try catch来捕获, 
  try catch是异步执行的, catch中return值, 处理之后就会被成功回调函数处理
  (2) 如果await的promise抛出异常, catch捕获异常是同步执行的, catch中return值, 处理之后就会被成功回调函数处理
  (3) await的promise对象失败状态不捕获, 抛出异常不捕获,返回的promise对象状态为失败状态, 执行失败回调函数
  
 -->
 <script type="text/javascript">
  // 1. 返回的promise对象
  // async function async1 () {
  //   // return Promise.resolve(3)
  //   // return '123'
  //   // 没有返回值 undefined
  //   // throw 2
  //   // throw new Error('出错了')
  //   await Promise.reject('出错了')
  // }
  // async1()
  // .then(res => {
  //   console.log(res)
  // })
  // .catch(err => {
  //   console.log(err)
  // })

  // 2. await 让出线程
  async function async2 () {
    await 1
    console.log('async2')
  }
  async2()
  .then(res => {
    console.log(res)
  })
  .catch(err => {
    console.log(err)
  })
  console.log('script end') //先于await语句后面的代码执行

 	async function fun1 () {
 		// try {
 			// var result = await 2 //同样让出线程
	 		var result = await fun2() //让出线程
	 		// var result = await fun3() //不是promise同样会让出线程
	 		// console.log(result)
	 		return 1 //promise 成功
	 		// throw 2 // promise 失败
	 		// return Promise.resolve(3)
	 		// return Promise.reject(4)
 		// } catch(error) {
 		// 	console.log(error)
 		// 	return 1
 		// }
 		

 	}
 	function fun2 () {
 		console.log('fun2')
 		// throw 'fun2 throw'
 		// return Promise.resolve('fun2 resolve')
 		return Promise.reject('fun2 reject')
 		

 	}
 	// function fun3 () {
 	// 	console.log('fun3')
 	// 	return 6
 	// }
 	// var result = fun1()
 	// console.log(result) //promise对象
 	// result
 	// .then(res => {
 	// 	console.log(res)
 	// })
 	// .catch(error => {
 	// 	console.log(error)
 	// })
 	// console.log('script end')
 </script>
</body>
</html>